---
  - name: Copy backend files
    copy:
      src: /root/project/backend/dist
      dest: /home/ubuntu

  - name: "install dependencies."
    become: true
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
  
  - name: Build
    become: true
    shell: |
      cd /home/ubuntu
      npm install
      npm run build
